### ISSUE TITLE
Settings get reset each time game is launched

### ISSUE THREAD

**Issue by AceHanded** [alexanderjoe/LCSymphony#2]
Hey!

With the release of v47, it would seem that the mod causes settings, such as the volume and mouse sensitivity to reset to 0, which is quite annoying.

-- AceHanded

**Comment by AmySchaplowsky** [comment]
I'm also experiencing this issue. Disabling the mod fixes the issue so I have isolated the issue to this mod specifically.

**Comment by alexanderjoe** [comment]
Which feature do you primarily use my mod for? Is it for the start menu skipping or the ping (latency) feature? There are some better menu-skipping option mods out there with more features (e.g. https://thunderstore.io/c/lethal-company/p/Owen3H/IntroTweaks/). 

I identified the issue to be part of the menu skipping sequence and it can be fixed to restore functionality (for a quick fix, set the config option for `LaunchOption` to `normal` to avoid the bug). However, I am looking to gauge if that is the primary use case of the mod anymore. Any feedback is appreciated @AmySchaplowsky & @AceHanded, thank you.

**Comment by AmySchaplowsky** [comment]
thanks for your suggestion into skip mods! I have switched to a different one!

**Comment by AceHanded** [comment]
I personally used your mod solely for skipping the start menu, and although I've never really used the ping feature, I think it's nice to have that option available.

Also, thanks for the referred mod, I guess I'll switch to a different one, at least for the time being. Good luck with your mod, whatever direction you decide to take it in!

**Comment by alexanderjoe** [comment]
@AceHanded just finally pushed a patch for the mod out. Would have been last night but Thunderstore was acting up and I couldn't upload it. Let me know if v1.3.0 fixes the issue you were seeing, it did for me at least.

**Comment by AceHanded** [comment]
Yeah, the latest version has fixed the issue. Thanks!
